import { type Metadata } from 'next';
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import { Geist, Geist_Mono } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}>
          <header className="flex justify-between items-center p-4 gap-4 h-16 bg-white shadow-sm border-b border-gray-100 fixed top-0 left-0 right-0 z-50">
            <div className="text-2xl font-bold text-gray-900">
              ProjectTracker
            </div>
            <div className="flex items-center gap-4">
              <SignedOut>
                <Link href="/sign-in">
                  <button className="text-black font-medium px-4 py-2 hover:text-gray-700 transition-colors">
                    Sign In
                  </button>
                </Link>
                <Link href="/sign-up">
                  <button className="text-black font-medium px-4 py-2 hover:text-gray-700 transition-colors">
                    Sign Up
                  </button>
                </Link>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>
          <div className="pt-16">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}